// The help widget's answer corpus, written against effGen 1.3.0.
//
// It lives in its own file because it is the part that goes stale: the matching
// engine in HelpBot.tsx is release-independent, this is not. When a release
// lands, this is the file to walk.
//
// Rules for anything added here:
//
//   - Every code sample was run against the released framework before it was
//     pasted. A sample that has not been run does not go in.
//   - Every count comes from data/effgen.json (via scripts/gen_site_data.py),
//     never from memory. Where a figure appears in prose here it was checked
//     against that file on 2026-08-18.
//   - Links are site-relative (`/docs/...`), so they survive a base path and
//     stay inside the site. The previous corpus used absolute
//     `https://www.effgen.org/docs/...` URLs, every one of which 404'd.
//   - Say what the software does. No superlatives.

export interface FAQ {
  id: number;
  category: string;
  question: string;
  answer: string;
  tags: string[]; // broad semantic tags used for matching
}

export const faqs: FAQ[] = [
  // ── Installation & setup ──────────────────────────────────────────────────
  {
    id: 1,
    category: "Installation",
    question: "How do I install effGen?",
    answer: [
      "```bash",
      "pip install -U effgen",
      "```",
      "",
      "The base install carries the agent loop, the built-in tools, the prompt library and every cloud provider adapter. Extras are opt-in:",
      "",
      "```bash",
      'pip install "effgen[vllm]"        # vLLM, for NVIDIA GPUs',
      'pip install "effgen[mlx]"         # MLX, for Apple Silicon',
      'pip install "effgen[local]"       # quantization + GGUF',
      'pip install "effgen[rag]"         # sentence-transformers + faiss',
      'pip install "effgen[server]"      # OIDC/JWT auth + Prometheus metrics',
      'pip install "effgen[all]"         # everything',
      "```",
      "",
      "Then check what your machine can actually reach:",
      "",
      "```bash",
      "effgen doctor",
      "```",
      "",
      "It reports which provider keys are set, what the system looks like, and what `effgen code` needs.",
      "",
      "Full matrix: /docs/installation",
    ].join("\n"),
    tags: ["install", "pip", "setup", "getting started", "installation", "how to install", "download", "extras", "doctor"],
  },
  {
    id: 2,
    category: "Installation",
    question: "What are the system requirements?",
    answer: [
      "- **Python 3.11, 3.12, 3.13 or 3.14.** 3.10 is not supported since 1.0.0 — that was one of its three breaking changes.",
      "- **RAM**: 8 GB is workable, 16 GB is comfortable.",
      "- **GPU**: only needed to run weights locally. Roughly 4 GB VRAM for a 3B model and 8 GB for a 7B at 4-bit.",
      "",
      "None of that applies if you are calling a provider — an API key is the only requirement, and CPU-only machines are fine.",
      "",
      "On 3.14 the `[all]` extra needs its lock file; see /docs/installation.",
    ].join("\n"),
    tags: ["requirements", "system", "hardware", "gpu", "ram", "cuda", "minimum", "specs", "cpu", "vram", "python version", "3.11", "3.14"],
  },
  {
    id: 3,
    category: "Installation",
    question: "How do I upgrade, and what breaks?",
    answer: [
      "```bash",
      "pip install -U effgen",
      "effgen --version",
      "```",
      "",
      "**From 1.2.0 to 1.3.0**, nothing was removed or renamed. Ten changes are visible to existing code; the ones most code meets first:",
      "",
      "1. **`max_turns_without_progress` defaults to `2`.** A run whose turns stop bringing new tool results is asked for its answer, and a stuck run gets one closing request. `None` restores 1.2.0's loop.",
      "2. **A tool that keeps failing on its own side ends the run `tool_failed`**, which raises `RunStoppedError` under the default `raise_on_error=True`.",
      "3. **`recover_lost_tool_calls` defaults to `True`**, so a tool call written in a broken shape runs and some runs make more tool calls. `False` restores 1.2.0's reader.",
      "4. **A served or local model is probed once** at `tool_calling_mode=\"auto\"`. `capability_probe=False` or `EFFGEN_CAPABILITY_PROBE=0` turns it off.",
      "",
      "**From 1.1.0 to 1.2.0**, nothing was removed or renamed. Fourteen changes are visible to existing code; the ones most code meets first:",
      "",
      "1. **A refused call under a spent cap raises `BudgetExceededError`** from `run()`, whatever `raise_on_error` says. It is not a `RuntimeError`, so catch it by name. A call that costs nothing is no longer refused.",
      "2. **A model with no published price reports cost as `None`**, not `0.0`, and a server reached with `base_url=` records as `openai_compatible`.",
      "3. **The tool contracts ask for less** and come before the caller's task; `AgentConfig(answer_style=...)` asks for a shorter or a fuller answer.",
      "4. **Every run keeps a ledger** — `response.ledger`. A decomposed run's `tokens_used` includes its sub-agents' tokens, and `execution_time` includes the post-run work.",
      "",
      "**From 1.0.1 to 1.1.0**, nothing was removed or renamed. Eleven changes are visible to existing code; the ones most code meets first:",
      "",
      "1. **`response.metadata[\"thread\"]` is the live `AgentThread`**, so `json.dumps(response.metadata)` raises. Serialise with `response.to_dict()`.",
      "2. **A session's earlier turns render differently in the prompt**, and travel as their own messages on a model that takes a conversation.",
      "3. **`stream()` now behaves like `run()`** — the same prompt, tools and sampling settings, and an output guardrail can stop it.",
      "4. **A run is bounded by `context_budget`** (`\"auto\"` by default). Pass `context_budget=None` for the old unbounded behaviour, and `Session(keep_thread_history=True)` if you read earlier turns' stored steps.",
      "",
      "**From 1.0.0 to 1.0.1**, nothing was removed or renamed, and four changes are visible to existing code:",
      "",
      "1. **A run that stops without an answer reports failure.** `success=False`, `outcome=\"stopped\"`, and the progress in `.partial`. Under the default `raise_on_error=True` it raises `RunStoppedError`, a `RuntimeError` subclass.",
      "2. **Citation markers are opt-in** — pass `cite_sources=True`. The `rag` preset already does.",
      "3. **A stream sends the model's working before its answer.**",
      "4. **A small local model writes more and calls tools more often**, because every path now says what the tools are for. `tool_use=\"sparing\"` tones that down.",
      "",
      "**From 0.3.x**, 1.0.0 also breaks three things:",
      "",
      "1. **Python 3.10 is no longer supported.** The floor is 3.11.",
      "2. **`AgentConfig.raise_on_error` now defaults to `True`.** A failed run raises instead of returning a result with `success=False`. Opt out with `raise_on_error=False` if your code checked the flag.",
      "3. **An unreachable backend raises `BackendUnreachableError`** regardless of that flag. There is no opt-out: a run that never reached a model has no result to report.",
      "",
      "The migration notes walk each one with the code change: /docs/migration",
    ].join("\n"),
    tags: ["upgrade", "update", "version", "latest", "pip upgrade", "changelog", "release", "breaking", "migration", "1.0.0", "1.0.1", "1.1.0", "1.2.0", "1.3.0"],
  },
  {
    id: 4,
    category: "Installation",
    question: "I'm getting a dependency or version conflict on install",
    answer: [
      "Start in a clean environment:",
      "",
      "```bash",
      "python -m venv effgen-env",
      "source effgen-env/bin/activate    # Windows: effgen-env\\Scripts\\activate",
      "pip install effgen",
      "```",
      "",
      "If the conflict involves **torch**, install torch first, against your driver's CUDA build, and only then install effGen — a later extra will otherwise pull a torch that does not match your driver and quietly disable the GPU:",
      "",
      "```bash",
      'pip install "torch>=2.0,<3" --index-url https://download.pytorch.org/whl/cu124',
      "pip install effgen",
      "```",
      "",
      "For `[all]`, use the published lock file rather than resolving freely. The full explanation, including the vLLM pinning problem, is at /docs/installation.",
    ].join("\n"),
    tags: ["version conflict", "dependency error", "install error", "virtual environment", "venv", "pip error", "conflict", "broken install", "torch", "cuda"],
  },

  // ── Models & providers ────────────────────────────────────────────────────
  {
    id: 5,
    category: "Models",
    question: "Which models and providers does effGen support?",
    answer: [
      "**Ten provider adapters**: `openai`, `anthropic`, `gemini`, `cerebras`, `groq`, `together`, `fireworks`, `replicate`, `hf` and `openai_compatible`. Nine of them ship a bundled catalog — 416 models with context windows and prices. `openai_compatible` ships none, because it serves whatever endpoint you point it at.",
      "",
      "**Four local engines** run weights on your own hardware: `transformers`, `vllm`, `gguf` and `mlx`.",
      "",
      "```python",
      "from effgen import load_model",
      "",
      'model = load_model("openai:gpt-5-nano")            # provider-prefixed',
      'model = load_model("gpt-5-nano", provider="openai")  # or bare id + provider',
      'model = load_model("Qwen/Qwen2.5-1.5B-Instruct")   # a local HuggingFace repo',
      "```",
      "",
      "Browse the catalog without writing any code:",
      "",
      "```bash",
      "effgen models browse",
      "```",
      "",
      "More: /docs/models · /docs/providers · /docs/catalog",
    ].join("\n"),
    tags: ["models", "supported", "providers", "which models", "model support", "backend", "openai", "anthropic", "gemini", "groq", "catalog", "load_model"],
  },
  {
    id: 6,
    category: "Models",
    question: "Can I point effGen at my own vLLM / Ollama / LM Studio server?",
    answer: [
      "Yes — that is the headline change in 1.0.0. Any server speaking the OpenAI protocol works: vLLM, SGLang, TGI, llama.cpp, Ollama, LM Studio, LiteLLM or a gateway.",
      "",
      "```python",
      "from effgen import load_model",
      "",
      "model = load_model(",
      '    "my-local-model",',
      '    provider="openai_compatible",',
      '    base_url="http://127.0.0.1:8000/v1",',
      ")",
      "```",
      "",
      "Two things worth knowing:",
      "",
      "- **The ids come from your server**, not from a bundled list. The adapter's `list_served_models()` asks the endpoint's `/models` route, and returns an empty list for a server that does not implement it.",
      "- **No price is invented.** An uncatalogued model reports no cost rather than a fabricated `$0`. If the server does not advertise a context window, effGen assumes 32,768 and says so — pass `context_length=` to set it exactly.",
      "",
      "Full page: /docs/openai-compatible",
    ].join("\n"),
    tags: ["vllm", "ollama", "lm studio", "sglang", "tgi", "llama.cpp", "litellm", "base_url", "openai compatible", "self hosted", "local server", "gateway", "endpoint"],
  },
  {
    id: 7,
    category: "Models",
    question: "How do I run a model locally instead of calling a provider?",
    answer: [
      "```python",
      "from effgen import load_model",
      "",
      "model = load_model(",
      '    "Qwen/Qwen2.5-1.5B-Instruct",',
      '    engine="vllm",          # or "transformers", "gguf", "mlx"',
      '    quantization="4bit",',
      ")",
      "```",
      "",
      "`engine=\"auto-fast\"` uses vLLM when it can import and falls back to Transformers when it cannot, which is the safer default on a machine whose torch build you are not sure about.",
      "",
      "To see what the machine can hold:",
      "",
      "```bash",
      "effgen models status",
      "```",
      "",
      "More: /docs/local-models · /docs/hardware",
    ].join("\n"),
    tags: ["local", "local model", "vllm", "transformers", "gguf", "mlx", "quantization", "4bit", "gpu", "offline", "self host"],
  },
  {
    id: 8,
    category: "Models",
    question: "Which model should I start with?",
    answer: [
      "For getting something working, start with a small hosted model — no weights to download and no GPU needed:",
      "",
      "```bash",
      'effgen run "What is 24344 * 334?" -m openai:gpt-5-nano',
      "```",
      "",
      "Then choose deliberately. `effgen models browse` filters the 416-model catalog by provider, capability, context window and price, and `effgen battle` runs several candidates on the same prompt so you can compare answers, cost and latency side by side:",
      "",
      "```bash",
      'effgen battle "Summarise the CAP theorem in three sentences" \\',
      "  -m openai:gpt-5-nano,gemini:gemini-3.1-flash-lite",
      "```",
      "",
      "effGen is built for small models first, so the interesting question is usually how small you can go before quality drops for *your* task — which is what `effgen eval` measures. See /docs/compare and /docs/evaluation.",
    ].join("\n"),
    tags: ["which model", "model size", "recommend", "start", "cheap", "small model", "slm", "battle", "compare", "choose"],
  },
  {
    id: 9,
    category: "Models",
    question: "How does effGen decide what a run cost?",
    answer: [
      "From the catalog, and only when the catalog actually knows. 1.0.0 stopped inventing prices, and since 1.2.0 an unpriced model's cost reads `None` everywhere it is added up:",
      "",
      "- A model with a catalogued price reports real cost, per model, and it adds up across a session.",
      "- An uncatalogued model, or a fine-tune (`ft:...`), reports **no** cost rather than `$0.00`.",
      "- Cost and tokens arrive on streamed responses too, not only on buffered ones.",
      "",
      "```python",
      "response = agent.run(task)",
      'print(response.metadata.get("cost_usd"))',
      "print(response.ledger.llm_calls, response.ledger.cost_usd)   # since 1.2.0",
      "```",
      "",
      "At the command line:",
      "",
      "```bash",
      "effgen cost today",
      "effgen cost by-provider",
      "```",
      "",
      "Budgets are set with `effgen cost set-budget`; a project scaffolded by `effgen quickstart --init` gets a $1.00/day cap if you set none. See /docs/cost.",
    ].join("\n"),
    tags: ["cost", "price", "pricing", "budget", "spend", "money", "billing", "tokens", "cheap", "expensive"],
  },

  // ── Getting started & concepts ────────────────────────────────────────────
  {
    id: 10,
    category: "Concepts",
    question: "How do I create my first agent?",
    answer: [
      "The shortest thing that works:",
      "",
      "```python",
      "from effgen import create_agent, load_env",
      "",
      "load_env()   # reads .env, so the key is not in your source",
      "",
      'agent = create_agent("math", "openai:gpt-5-nano")',
      'response = agent.run("What is 24344 * 334?")',
      "",
      "print(response.output)      # 8130896",
      "print(response.success)     # True",
      "```",
      "",
      "`create_agent` takes a preset — one of nine — and a model. To build the configuration yourself instead:",
      "",
      "```python",
      "from effgen import Agent, load_model",
      "from effgen.core.agent import AgentConfig",
      "from effgen.tools.builtin import Calculator, PythonREPL",
      "",
      'model = load_model("openai:gpt-5-nano")',
      "agent = Agent(AgentConfig(",
      '    name="math_agent",',
      "    model=model,",
      "    tools=[Calculator(), PythonREPL()],",
      "))",
      "```",
      "",
      "Walkthrough: /docs/quickstart",
    ].join("\n"),
    tags: ["first agent", "create agent", "getting started", "hello world", "example", "quickstart", "create_agent", "how to start", "beginner"],
  },
  {
    id: 11,
    category: "Concepts",
    question: "What are presets?",
    answer: [
      "A preset is a ready-made agent configuration — a system prompt, a tool set, a temperature and an iteration cap — for a kind of work. There are **nine**: `math`, `research`, `coding`, `general`, `rag`, `minimal`, `multimodal`, `notify` and `media`.",
      "",
      "```bash",
      "effgen presets            # what each one is and what it carries",
      "```",
      "",
      "```python",
      "from effgen import create_agent",
      "",
      'agent = create_agent("research", "openai:gpt-5-nano")',
      "```",
      "",
      "Anything a preset sets can be overridden at the call:",
      "",
      "```python",
      "agent = create_agent(",
      '    "coding",',
      '    "openai:gpt-5-nano",',
      "    temperature=0.2,",
      '    extra_tools=["web_search"],',
      ")",
      "```",
      "",
      "More: /docs/presets",
    ].join("\n"),
    tags: ["preset", "presets", "math", "research", "coding", "rag", "minimal", "multimodal", "create_agent", "configuration"],
  },
  {
    id: 12,
    category: "Concepts",
    question: "What does an agent run actually do?",
    answer: [
      "It is a loop. The model is given the task and the tools it may call; it reasons, picks a tool, sees the result, and repeats until it can answer or hits the iteration cap.",
      "",
      "1.0.0 made that loop legible. `AgentResponse.tool_calls` carries what actually happened:",
      "",
      "```python",
      "response = agent.run(task)",
      "",
      "for call in response.tool_calls:",
      "    print(call.name, call.arguments, call.result, call.duration)",
      "",
      "print(len(response.tool_calls))   # still works as a count",
      "print(response.tool_calls.failed) # only the ones that errored",
      'print(response.tool_calls.by_name("calculator"))',
      "```",
      "",
      "`response.execution_trace` and `response.execution_tree` carry the fuller record, including sub-agent work.",
      "",
      "More: /docs/agents",
    ].join("\n"),
    tags: ["react", "loop", "how it works", "reasoning", "iterations", "tool_calls", "trace", "agent loop", "observation", "action"],
  },
  {
    id: 13,
    category: "Concepts",
    question: "How do I give one agent several separate conversations?",
    answer: [
      "Pass a session. Each session keeps its own history; the agent, its tools and its model are shared.",
      "",
      "```python",
      'agent = create_agent("general", "openai:gpt-5-nano")',
      "",
      'agent.run("My name is Ada.", session="user-1")',
      'agent.run("My name is Grace.", session="user-2")',
      "",
      'agent.run("What is my name?", session="user-1")   # Ada',
      "```",
      "",
      "That is new in 1.0.0 — before it, one agent meant one conversation. Sessions are durable and browsable from the command line:",
      "",
      "```bash",
      "effgen sessions list",
      "effgen sessions show <id>",
      "effgen sessions export <id>",
      "```",
      "",
      "More: /docs/sessions",
    ].join("\n"),
    tags: ["session", "sessions", "conversation", "history", "multi user", "memory", "run session", "context", "chat history"],
  },
  {
    id: 14,
    category: "Concepts",
    question: "What happens when the conversation gets too long for the context window?",
    answer: [
      "You choose. 1.0.0 makes compaction pluggable rather than fixed:",
      "",
      "```python",
      "from effgen import SummarizeOldest, KeepFirstAndLast, DropOldest, KeepToolResults",
      "```",
      "",
      "- `SummarizeOldest` — replaces the oldest turns with a summary.",
      "- `KeepFirstAndLast` — keeps the opening and the recent turns, drops the middle.",
      "- `DropOldest` — drops the oldest turns outright.",
      "- `KeepToolResults` — drops prose before it drops what a tool returned.",
      "",
      "Which one is right depends on whether the early turns carry instructions you cannot lose, or facts a summary would blur. More: /docs/compaction",
    ].join("\n"),
    tags: ["compaction", "context window", "too long", "truncate", "summarize", "history", "token limit", "context length", "overflow"],
  },
  {
    id: 15,
    category: "Concepts",
    question: "How does agent memory work?",
    answer: [
      "Memory is separate from conversation history: history is what was said, memory is what is worth keeping.",
      "",
      "```python",
      'agent = create_agent("general", "openai:gpt-5-nano", enable_memory=True)',
      "```",
      "",
      "Short-term memory holds the working context of a run. Long-term memory is a vector store the agent can search — the same machinery RAG uses, which is why a `rag` preset agent can take a pre-built store as its `knowledge_base`.",
      "",
      "More: /docs/memory · /docs/rag",
    ].join("\n"),
    tags: ["memory", "long term", "short term", "remember", "vector", "store", "recall", "enable_memory"],
  },
  {
    id: 16,
    category: "Concepts",
    question: "What is middleware and when would I use it?",
    answer: [
      "Middleware wraps the agent loop so you can observe or intervene without editing the loop. New in 1.0.0.",
      "",
      "```python",
      "from effgen import LoggingMiddleware, ToolApprovalMiddleware, MiddlewareChain",
      "```",
      "",
      "Hooks run before and after the whole run, each model call, and each tool call. Two ship with the framework:",
      "",
      "- `LoggingMiddleware` — records what the loop did.",
      "- `ToolApprovalMiddleware` — holds a tool call until it is approved, which is how you put a human in front of anything that writes.",
      "",
      "Write your own by subclassing `AgentMiddleware`, and compose several with `MiddlewareChain`. More: /docs/middleware",
    ].join("\n"),
    tags: ["middleware", "hooks", "intercept", "approval", "logging", "before", "after", "wrap", "human in the loop"],
  },

  // ── Tools ─────────────────────────────────────────────────────────────────
  {
    id: 17,
    category: "Tools",
    question: "What built-in tools are there?",
    answer: [
      "**66**, in eight categories:",
      "",
      "- **information_retrieval** (20) — web and academic search, Wikipedia, arXiv, PubMed, GitHub, Reddit, Hacker News, RSS, YouTube, URL fetch",
      "- **data_processing** (16) — PDF, DOCX, Excel, OCR, plotting, dataframes, translation, audio transcription, QR",
      "- **external_api** (8) — weather, geocoding, maps, stock and crypto prices, currency, HTTP, Wolfram Alpha",
      "- **communication** (7) — email over SMTP and IMAP, Slack, Discord, notifications",
      "- **code_execution** (6) — a sandboxed Python REPL, a code executor, and the provider-native ones",
      "- **system** (4) — bash, git, docker, system info",
      "- **computation** (3) — calculator, datetime, stats",
      "- **file_operations** (2)",
      "",
      "```bash",
      "effgen tools list",
      "effgen tools info calculator",
      "```",
      "",
      "The full gallery, with a runnable example per tool: /docs/tools/gallery",
    ].join("\n"),
    tags: ["tools", "built-in", "available tools", "list tools", "what tools", "66", "categories", "gallery"],
  },
  {
    id: 18,
    category: "Tools",
    question: "How do I call a tool directly?",
    answer: [
      "`execute` is a coroutine and takes keyword arguments. It returns a `ToolResult`:",
      "",
      "```python",
      "import asyncio",
      "from effgen.tools.builtin import Calculator",
      "",
      "async def main():",
      "    tool = Calculator()",
      '    result = await tool.execute(expression="24344 * 334")',
      "    print(result.success)   # True",
      "    print(result.output)    # {'result': 8130896, 'formatted': '8130896', ...}",
      "",
      "asyncio.run(main())",
      "```",
      "",
      "**Two shapes that do not work**, and that older material still shows:",
      "",
      "- `await tool.execute({\"expression\": ...})` — a dict positional raises `TypeError`. Pass keywords.",
      "- `result[\"data\"][...]` — `ToolResult` is not subscriptable and has no `data` field.",
      "",
      "The fields are `success`, `output`, `error`, `execution_time`, `metadata` and `timestamp`. See /docs/tools",
    ].join("\n"),
    tags: ["tool", "execute", "call tool", "toolresult", "output", "data", "await", "kwargs", "directly", "api"],
  },
  {
    id: 19,
    category: "Tools",
    question: "How do I write my own tool?",
    answer: [
      "The decorator is the short way — the signature and the docstring become the schema the model sees:",
      "",
      "```python",
      "from effgen import tool",
      "",
      "@tool",
      "def word_count(text: str) -> int:",
      '    """Count the words in a piece of text."""',
      "    return len(text.split())",
      "```",
      "",
      "Then hand it to an agent:",
      "",
      "```python",
      'agent = create_agent("general", "openai:gpt-5-nano", extra_tools=[word_count])',
      "```",
      "",
      "`Tool.from_function` does the same for a function you cannot decorate. For anything with setup, teardown or its own error handling, subclass `BaseTool`.",
      "",
      "To ship one as an installable package, `effgen create-plugin` scaffolds it and installed plugins are discovered automatically. See /docs/custom-tools",
    ].join("\n"),
    tags: ["custom tool", "write tool", "@tool", "decorator", "from_function", "basetool", "plugin", "extend", "own tool"],
  },
  {
    id: 20,
    category: "Tools",
    question: "Is code execution sandboxed?",
    answer: [
      "Yes. The Python REPL and the code executor run in a sandbox with a timeout enforced from outside the executed code, so a program that blocks cannot hold the agent.",
      "",
      "The sandbox reports what it enforced: `SandboxResult.credential_reads_masked` and `.process_table_isolated` tell you that credential stores were masked and that the code ran in its own PID namespace rather than seeing the host's process table.",
      "",
      "A `DockerSandbox` is available where you want a container boundary instead. Whether the sandbox is on is not a decision the model can make.",
      "",
      "More: /docs/execution",
    ].join("\n"),
    tags: ["sandbox", "code execution", "python repl", "security", "safe", "docker", "timeout", "isolation", "untrusted"],
  },
  {
    id: 21,
    category: "Tools",
    question: "Can I use a provider's own tools, like OpenAI web search?",
    answer: [
      "Yes — the ones the provider runs on its side, rather than in your process:",
      "",
      "- **OpenAI**: web search, code interpreter, file search",
      "- **Gemini**: Google Search grounding, URL context, code execution",
      "- **Anthropic**: bash, text editor, computer use",
      "",
      "They are used like any other tool, and what they return lands in `response.tool_calls` alongside the local ones. Where a provider returns grounding citations, those populate `response.sources` and `response.citations` from the URLs the run actually retrieved — not from the model's prose.",
      "",
      "More: /docs/native-provider-tools",
    ].join("\n"),
    tags: ["native tools", "provider tools", "web search", "code interpreter", "file search", "grounding", "google search", "computer use", "bash tool"],
  },
  {
    id: 22,
    category: "Tools",
    question: "Does effGen support MCP?",
    answer: [
      "Yes, along with two other protocols: **MCP** (Model Context Protocol) for tool servers, **A2A** for agent-to-agent messaging, and **ACP** for agent communication.",
      "",
      "An MCP server's tools appear as ordinary effGen tools once connected, so nothing else in your code changes. Calling an MCP stdio tool from synchronous `Agent.run()` no longer deadlocks — it raises a clear `TimeoutError` if the server does not answer.",
      "",
      "More: /docs/protocols",
    ].join("\n"),
    tags: ["mcp", "model context protocol", "a2a", "acp", "protocol", "server", "interop", "agent to agent"],
  },

  // ── The command line ──────────────────────────────────────────────────────
  {
    id: 23,
    category: "CLI",
    question: "What can the effgen command line do?",
    answer: [
      "**29 commands**, with 38 sub-commands under them. The ones worth knowing first:",
      "",
      "```bash",
      'effgen run "task" -m openai:gpt-5-nano   # one task, one answer',
      "effgen chat                              # interactive",
      "effgen code                              # the coding agent",
      "effgen serve                             # the API server",
      "effgen top                               # live runs, traffic, spend, GPU",
      "effgen battle                            # several models, one prompt",
      "effgen doctor                            # what is configured and reachable",
      "effgen quickstart --init                 # scaffold a project",
      "```",
      "",
      "Every command takes `--json` and emits a single valid document on a pipe, so it scripts. `--theme` picks among `default`, `high-contrast`, `monochrome` and `light`, and `--completion bash|zsh|fish` prints a completion script.",
      "",
      "More: /docs/cli",
    ].join("\n"),
    tags: ["cli", "command line", "commands", "terminal", "effgen run", "json", "shell", "completion", "theme"],
  },
  {
    id: 24,
    category: "CLI",
    question: "What is effgen code?",
    answer: [
      "A coding agent that runs in your terminal: it reads the repository, proposes changes as unified diffs, applies them, runs what it wrote, and fixes what fails.",
      "",
      "```bash",
      "effgen code",
      "```",
      "",
      "It has **four permission modes** — `plan` (propose only), `ask` (confirm each edit), `auto-edit` (edit freely, confirm commands) and `yes` (no prompts) — and a git allow-list bounding what it may run.",
      "",
      "```bash",
      "effgen code --undo             # step back through a 100-entry journal",
      "effgen code --review           # review the working tree instead of editing",
      "effgen code --session-id work  # resume a named session",
      'effgen code -p "add a test for parse_config" --json',
      "```",
      "",
      "It reads `AGENTS.md` if the repository has one, streams its answers, and has 26 slash commands inside the session. New in 1.0.0. More: /docs/cli/code",
    ].join("\n"),
    tags: ["effgen code", "coding agent", "diff", "permission", "undo", "review", "terminal", "repository", "agents.md", "slash commands"],
  },
  {
    id: 25,
    category: "CLI",
    question: "How do I watch what my agents are doing?",
    answer: [
      "```bash",
      "effgen top          # or: effgen monitor",
      "```",
      "",
      "A live terminal view with panels for activity, traffic, per-model use, spend and GPU. It reads the same durable run history the rest of the tooling does, so it shows scripted runs and server traffic, not only what you started by hand.",
      "",
      "For the record after the fact:",
      "",
      "```bash",
      "effgen runs list --status failed",
      "effgen runs show <id> --card",
      "```",
      "",
      "More: /docs/cli/top · /docs/cli/history",
    ].join("\n"),
    tags: ["top", "monitor", "watch", "live", "dashboard", "terminal", "runs", "history", "activity", "spend", "gpu"],
  },
  {
    id: 26,
    category: "CLI",
    question: "Can I get an HTML report out of a run?",
    answer: [
      "Yes. `compare`, `eval`, `cost` and `loadtest` all take `--report`, and a single run can produce a card:",
      "",
      "```bash",
      "effgen compare -m openai:gpt-5-nano,gemini:gemini-3.1-flash-lite \\",
      "  --suite math --report compare.html",
      "",
      'effgen run "task" --card',
      "effgen runs show <id> --card",
      "```",
      "",
      "A saved JSON result can be rendered later:",
      "",
      "```bash",
      "effgen report result.json -o result.html",
      "```",
      "",
      "The output is a self-contained file you can send to someone. More: /docs/cli/reports",
    ].join("\n"),
    tags: ["report", "html", "card", "share", "export", "compare", "eval", "loadtest", "output"],
  },
  {
    id: 27,
    category: "CLI",
    question: "How do I start a new project?",
    answer: [
      "```bash",
      "effgen quickstart --init my-project",
      "```",
      "",
      "That writes an `effgen.yaml`, an `.env.example`, and a runnable starting point — and sets a **$1.00/day** spend cap if you have not configured one, so an experiment cannot run up a bill unnoticed.",
      "",
      "For configuration on its own:",
      "",
      "```bash",
      "effgen config init",
      "effgen config show",
      "effgen config validate",
      "```",
      "",
      "`effgen run -c my.yaml` runs against a specific configuration file. More: /docs/first-project · /docs/configuration",
    ].join("\n"),
    tags: ["quickstart", "init", "new project", "scaffold", "effgen.yaml", "config", "setup", "budget", "template"],
  },

  // ── Orchestration ─────────────────────────────────────────────────────────
  {
    id: 28,
    category: "Multi-Agent",
    question: "How do I run several agents together?",
    answer: [
      "Two shapes, and they answer different questions.",
      "",
      "**A team** is several agents collaborating on one task, routed by name. It fails closed: a message addressed to an agent that does not exist is an error, not a silent drop.",
      "",
      "**A workflow** is a DAG — explicit steps with explicit dependencies — when you know the shape of the work in advance:",
      "",
      "```python",
      "from effgen import WorkflowDAG",
      "```",
      "",
      "```bash",
      "effgen workflow run pipeline.yaml --diagram",
      "```",
      "",
      "`--diagram` prints the graph so you can check the shape before running it. More: /docs/multi-agent · /docs/workflows",
    ].join("\n"),
    tags: ["multi agent", "team", "workflow", "dag", "orchestration", "collaborate", "pipeline", "several agents", "sub agents"],
  },
  {
    id: 29,
    category: "Multi-Agent",
    question: "Can a workflow resume after it dies half way through?",
    answer: [
      "Yes, new in 1.0.0. Give the run a checkpoint store and an id:",
      "",
      "```python",
      "from effgen import WorkflowDAG, FileCheckpointStore",
      "",
      "dag.run(",
      '    checkpoint=FileCheckpointStore(),',
      '    run_id="nightly-2026-08-18",',
      ")",
      "```",
      "",
      "Run it again with the same `run_id` and the completed steps are skipped. `InMemoryCheckpointStore` is the test-time equivalent, and `CheckpointStore` is the interface if you want to keep checkpoints somewhere else.",
      "",
      "For an interrupted single run rather than a workflow, `effgen resume` picks it back up — since 1.1.0 it continues from the run's saved steps rather than restarting the task. More: /docs/checkpointing",
    ].join("\n"),
    tags: ["checkpoint", "resume", "restart", "crash", "workflow", "dag", "run_id", "recover", "idempotent", "interrupted"],
  },

  // ── Production ────────────────────────────────────────────────────────────
  {
    id: 30,
    category: "Production",
    question: "How do I serve effGen as an API?",
    answer: [
      "```bash",
      "effgen serve",
      "```",
      "",
      "It exposes an **OpenAI-compatible** API, so an existing OpenAI client can point at it by changing its `base_url` and nothing else. It carries auth, RBAC, an audit log, rate limiting, Prometheus metrics and tracing.",
      "",
      "Note that `effgen serve` takes **no** `--model` and **no** `--quantization` — the model comes from your configuration, not the serve command. `effgen serve --help` is the authority.",
      "",
      "To check it under load:",
      "",
      "```bash",
      "effgen loadtest --url http://127.0.0.1:8000",
      "```",
      "",
      "More: /docs/api-server · /docs/openai-api",
    ].join("\n"),
    tags: ["serve", "api", "server", "rest", "openai compatible", "deploy", "production", "auth", "rbac", "endpoint", "loadtest"],
  },
  {
    id: 31,
    category: "Production",
    question: "What can I see about a running deployment?",
    answer: [
      "- **Metrics**: Prometheus histograms labelled by provider, model and status, with SLO and alerting exports at the top level.",
      "- **Tracing**: OpenTelemetry spans with samplers and a documented span spec.",
      "- **Logs**: structured JSON with secret redaction.",
      "- **Reliability**: circuit breakers, bulkheads, jittered retries, and a chaos harness to prove they fire.",
      "",
      "A failure is classified rather than guessed at — `metadata[\"error\"][\"category\"]` is one of `auth`, `not_found`, `rate_limited`, `transient`, `timeout` or `fatal`, so a retry happens only when retrying could help.",
      "",
      "More: /docs/observability · /docs/metrics · /docs/tracing · /docs/slos · /docs/reliability",
    ].join("\n"),
    tags: ["observability", "metrics", "prometheus", "tracing", "otel", "logs", "slo", "alerting", "monitoring", "reliability", "circuit breaker"],
  },
  {
    id: 32,
    category: "Production",
    question: "How do I deploy it?",
    answer: [
      "Four supported shapes, each with files in the repository:",
      "",
      "- **Docker** — a multi-stage, non-root image",
      "- **Kubernetes** — a Helm chart with HPA and PDB",
      "- **AWS Lambda** — through Mangum",
      "- **Cloudflare** — an edge proxy Worker",
      "",
      "More: /docs/deployment",
    ].join("\n"),
    tags: ["deploy", "deployment", "docker", "kubernetes", "helm", "k8s", "lambda", "aws", "cloudflare", "container", "production"],
  },
  {
    id: 33,
    category: "Production",
    question: "How do I stop an agent doing something it shouldn't?",
    answer: [
      "Guardrails run on input and output and can block, redact or rewrite:",
      "",
      "```python",
      'agent = create_agent("general", "openai:gpt-5-nano", guardrails=[...])',
      "```",
      "",
      "The framework ships PII and PHI redaction, prompt-injection checks, and `SystemPromptLeakGuardrail`, which is new in 1.0.0 and catches a response that is quoting your system prompt back.",
      "",
      "For actions rather than text, `ToolApprovalMiddleware` holds a tool call until a human approves it — the right control for anything that writes, sends or spends.",
      "",
      "More: /docs/guardrails · /docs/human-loop · /docs/security",
    ].join("\n"),
    tags: ["guardrails", "safety", "pii", "phi", "redaction", "injection", "block", "approval", "human in the loop", "security", "leak"],
  },
  {
    id: 34,
    category: "Production",
    question: "How do I know a change didn't make things worse?",
    answer: [
      "Run an evaluation and gate on it:",
      "",
      "```bash",
      "effgen eval --suite math -m openai:gpt-5-nano --fail-under 0.8",
      "```",
      "",
      "It exits non-zero below the threshold, which is what makes it usable as a CI gate. `--save-baseline` and `--compare-baseline` turn it into a regression check between runs.",
      "",
      "To compare candidates rather than gate one:",
      "",
      "```bash",
      "effgen compare -m openai:gpt-5-nano,gemini:gemini-3.1-flash-lite --suite math",
      "```",
      "",
      "More: /docs/evaluation · /docs/compare",
    ].join("\n"),
    tags: ["eval", "evaluation", "test", "ci", "regression", "baseline", "quality", "accuracy", "gate", "compare", "benchmark"],
  },

  // ── RAG & data ────────────────────────────────────────────────────────────
  {
    id: 35,
    category: "Concepts",
    question: "How do I do RAG over my own documents?",
    answer: [
      "The `rag` preset wires retrieval into the agent loop:",
      "",
      "```python",
      "from effgen import create_agent",
      "",
      'agent = create_agent("rag", "openai:gpt-5-nano", knowledge_base=store)',
      "```",
      "",
      "`knowledge_base` takes a pre-built `VectorMemoryStore`, so you can index once and reuse it. Retrieval is hybrid — dense and keyword — rather than embedding-only.",
      "",
      "Install the extra first:",
      "",
      "```bash",
      'pip install "effgen[rag]"',
      "```",
      "",
      "More: /docs/rag",
    ].join("\n"),
    tags: ["rag", "retrieval", "documents", "knowledge base", "vector", "embeddings", "search", "index", "pdf", "faiss"],
  },
  {
    id: 36,
    category: "Concepts",
    question: "Can it read images, audio or video?",
    answer: [
      "Yes, across the providers that support each. The `multimodal` preset is the quick way in, and `MultimodalDescribeTool` handles a mixed input.",
      "",
      "```python",
      'agent = create_agent("multimodal", "gemini:gemini-3.1-flash-lite")',
      "```",
      "",
      "For files rather than a conversation, the tool set covers OCR, audio transcription, image captioning and metadata, and document parsing for PDF, DOCX and Excel.",
      "",
      "More: /docs/multimodal",
    ].join("\n"),
    tags: ["multimodal", "image", "audio", "video", "vision", "ocr", "transcribe", "picture", "speech", "pdf"],
  },
  {
    id: 37,
    category: "Concepts",
    question: "Can I get structured output instead of prose?",
    answer: [
      "Yes. Give the run a schema and the answer comes back matching it:",
      "",
      "```bash",
      "effgen batch queries.jsonl --schema schema.json",
      "```",
      "",
      "Provider-side structured output is used where the provider supports it; for local models the output is grammar-constrained rather than merely asked for, so it conforms rather than usually conforming.",
      "",
      "More: /docs/generation",
    ].join("\n"),
    tags: ["structured output", "json", "schema", "parse", "format", "pydantic", "grammar", "constrained", "typed"],
  },

  // ── Prompts ───────────────────────────────────────────────────────────────
  {
    id: 38,
    category: "Concepts",
    question: "What is the prompt library?",
    answer: [
      "**35 evaluated prompt templates across 8 domains** — business, coding, creative, data, education, legal, medical and research. (The framework registers 41 templates in total; 35 are in the library the CLI lists.)",
      "",
      "```bash",
      "effgen prompts list",
      "effgen prompts list --domain research",
      "effgen prompts show <name>                       # its input schema",
      "effgen prompts render <name>                     # render to stdout",
      "effgen prompts run <name> -m openai:gpt-5-nano   # render, then run it",
      "```",
      "",
      "`prompts run` takes its variables from a JSON file passed with `-i`, validated against the input schema `prompts show` prints; omit it and the prompt's own fixture is rendered. It reports what the run cost. `effgen prompts playground` is the interactive way to iterate on one.",
      "",
      "Your own templates go in `EFFGEN_PROMPTS_DIR`. More: /docs/prompts · /docs/prompts/gallery",
    ].join("\n"),
    tags: ["prompts", "templates", "library", "domain", "playground", "prompt engineering", "35", "render", "variables"],
  },

  // ── Performance ───────────────────────────────────────────────────────────
  {
    id: 39,
    category: "Performance",
    question: "How do I make it faster?",
    answer: [
      "It depends where the time is going, so measure first — `effgen top` and the per-run latency in `response.metadata` tell you whether you are waiting on the model, on tools, or on iterations.",
      "",
      "The usual wins:",
      "",
      "- **Fewer iterations.** A tighter system prompt and a smaller tool set beat a faster model.",
      "- **A smaller model.** effGen is built for that; `effgen eval` tells you how small you can go before quality drops on your task.",
      "- **vLLM instead of Transformers** for local weights under throughput.",
      "- **A faster provider.** `effgen battle` shows latency side by side.",
      "",
      "More: /docs/hardware · /docs/evaluation",
    ].join("\n"),
    tags: ["fast", "faster", "performance", "speed", "latency", "slow", "optimize", "throughput", "vllm", "benchmark"],
  },
  {
    id: 40,
    category: "Performance",
    question: "Does it stream?",
    answer: [
      "Yes, on every adapter, and streaming no longer costs you the bookkeeping: cost and token counts arrive on a streamed response the same as a buffered one.",
      "",
      "`effgen run` and `effgen chat` stream by default in the terminal, and `effgen code` streams its answers as it works.",
      "",
      "More: /docs/generation",
    ].join("\n"),
    tags: ["stream", "streaming", "token by token", "realtime", "sse", "incremental", "live"],
  },

  // ── Troubleshooting ───────────────────────────────────────────────────────
  {
    id: 41,
    category: "Troubleshooting",
    question: "My run raises instead of returning success=False",
    answer: [
      "That is behaving as designed. `AgentConfig.raise_on_error` defaults to `True` (since 1.0.0), so a failure raises rather than being handed back as a result you might not check. Since 1.0.1 a run the loop stopped before the model wrote an answer raises `RunStoppedError`, which carries `.response`, `.stop_reason` and `.partial`.",
      "",
      "To get the old behaviour:",
      "",
      "```python",
      "from effgen.core.agent import AgentConfig",
      "",
      "config = AgentConfig(..., raise_on_error=False)",
      "```",
      "",
      "One case has no opt-out: an **unreachable backend** raises `BackendUnreachableError` whatever the flag says, because a run that never reached a model has no result to report.",
      "",
      "More: /docs/migration · /docs/errors",
    ].join("\n"),
    tags: ["raise", "exception", "error", "raise_on_error", "success", "false", "breaking", "backendunreachable", "runstoppederror", "stopped", "1.0.0", "1.0.1", "migration"],
  },
  {
    id: 42,
    category: "Troubleshooting",
    question: "I get an authentication or API key error",
    answer: [
      "Check what is actually configured and reachable:",
      "",
      "```bash",
      "effgen doctor",
      "effgen doctor --live --cheap   # actually call each provider, cheaply",
      "```",
      "",
      "Keys are read from the environment, and `load_env()` reads a `.env` file so they stay out of your source:",
      "",
      "```python",
      "from effgen import load_env",
      "load_env()",
      "```",
      "",
      "The variable names follow the provider: `OPENAI_API_KEY`, `ANTHROPIC_API_KEY`, `GEMINI_API_KEY`, `GROQ_API_KEY`, and so on. An error here names the variable it wanted rather than saying \"unauthorized\".",
      "",
      "More: /docs/configuration",
    ].join("\n"),
    tags: ["api key", "auth", "authentication", "401", "unauthorized", "env", "environment variable", "doctor", "load_env", "credentials"],
  },
  {
    id: 43,
    category: "Troubleshooting",
    question: "A model id I used before no longer exists",
    answer: [
      "Catalogs move. Three ids that appear in older material and are gone:",
      "",
      "- **`llama3.1-8b` on Cerebras** — Cerebras now serves `gpt-oss-120b` and `zai-glm-4.7`.",
      "- **`gemini-2.0-flash` / `gemini-2.0-flash-lite`** — use `gemini-3.1-flash-lite`.",
      "",
      "Check what a provider serves today rather than trusting a snapshot:",
      "",
      "```bash",
      "effgen models list --provider cerebras",
      "effgen models browse --provider gemini",
      "effgen models refresh          # re-read the live catalog",
      "```",
      "",
      "`effgen models refresh` also warns when the bundled catalog has drifted. More: /docs/catalog",
    ].join("\n"),
    tags: ["model not found", "404", "invalid model", "deprecated", "cerebras", "gemini", "llama3.1-8b", "catalog", "refresh", "drift"],
  },
  {
    id: 44,
    category: "Troubleshooting",
    question: "The agent stops before it finishes the task",
    answer: [
      "Usually the iteration cap, or a guard ending a run that repeats itself. effGen reports that as what it is rather than presenting a partial answer as a complete one: `response.outcome` is `\"stopped\"`, `response.stop_reason` names the exit (`max_iterations_partial`, `loop_detected`, ...), and `response.partial` carries what it had got to. Under the default `raise_on_error=True` the run raises `RunStoppedError` with the same three.",
      "",
      "```python",
      "agent = create_agent(",
      '    "research", "openai:gpt-5-nano",',
      "    max_iterations=20,",
      ")",
      "```",
      "",
      "If it is stopping for another reason, `response.execution_trace` shows where the loop went, and `effgen debug` runs the same task step by step:",
      "",
      "```bash",
      'effgen debug "your task" --step',
      "```",
      "",
      "More: /docs/debug",
    ].join("\n"),
    tags: ["stops", "stopped", "incomplete", "max iterations", "partial", "truncated", "loop", "cap", "unfinished", "debug", "trace", "stop_reason", "outcome", "runstoppederror"],
  },
  {
    id: 45,
    category: "Troubleshooting",
    question: "A tool call fails and I can't tell why",
    answer: [
      "The call is on the response, with its error:",
      "",
      "```python",
      "for call in response.tool_calls.failed:",
      "    print(call.name, call.arguments, call.error)",
      "```",
      "",
      "For the tool on its own, `ToolResult.error` carries the message and `ToolResult.metadata` the context. Error messages name the fix rather than the symptom — a scheme-less URL names the variable that needs one, a connection failure names the endpoint it could not reach, and a 413 whose provider code reads `rate_limit_exceeded` is reported as the oversized request it actually is, with what to shorten.",
      "",
      "```bash",
      "effgen tools test <name>",
      "```",
      "",
      "More: /docs/errors · /docs/debug",
    ].join("\n"),
    tags: ["tool fails", "tool error", "failed", "debug", "toolresult", "error message", "exception", "diagnose"],
  },
  {
    id: 46,
    category: "Troubleshooting",
    question: "It's slower or heavier than I expected on GPU",
    answer: [
      "First check what the machine has and what is loaded:",
      "",
      "```bash",
      "effgen models status",
      "```",
      "",
      "It reports physical GPU memory, not just what the allocator thinks it holds.",
      "",
      "The most common cause is a torch build that does not match the driver — which happens when an extra pulls torch after the fact. Install torch against your CUDA version first, then effGen. `engine=\"auto-fast\"` falls back to Transformers when vLLM cannot import, which is quiet but slow; if you expected vLLM, check that it imports.",
      "",
      "More: /docs/hardware · /docs/installation",
    ].join("\n"),
    tags: ["gpu", "slow", "vram", "out of memory", "oom", "cuda", "torch", "vllm", "memory", "driver", "status"],
  },

  // ── Configuration ─────────────────────────────────────────────────────────
  {
    id: 47,
    category: "Configuration",
    question: "How do I configure effGen?",
    answer: [
      "Three layers, in increasing precedence: an `effgen.yaml` file, environment variables, and arguments at the call.",
      "",
      "```bash",
      "effgen config init        # write a starting effgen.yaml",
      "effgen config show        # what is in effect now",
      "effgen config validate    # check it before a run depends on it",
      "effgen config set <key> <value>",
      "```",
      "",
      "```bash",
      "effgen run -c ./my-config.yaml \"task\"",
      "```",
      "",
      "More: /docs/configuration",
    ].join("\n"),
    tags: ["config", "configuration", "yaml", "settings", "effgen.yaml", "environment", "options", "defaults"],
  },
  {
    id: 48,
    category: "Configuration",
    question: "Where do API keys go?",
    answer: [
      "In the environment, or in a `.env` file that is never committed.",
      "",
      "```bash",
      "cp .env.example .env      # effgen quickstart --init writes both",
      "```",
      "",
      "```python",
      "from effgen import load_env",
      "load_env()                # then create_agent(...) as normal",
      "```",
      "",
      "Never in source, and never in an `effgen.yaml` you commit. The audit log and the structured logs redact secrets, and the sandbox masks credential stores from executed code — but the first line of defence is that the key was never written down in the repository.",
      "",
      "More: /docs/configuration · /docs/security",
    ].join("\n"),
    tags: ["api key", "secret", "env", ".env", "credentials", "load_env", "environment variable", "security", "token"],
  },

  // ── Releases ──────────────────────────────────────────────────────────────
  {
    id: 64,
    category: "Releases",
    question: "What's new in 1.3.0?",
    answer: [
      "1.3.0 is out on **1 October 2026**. It is about how a run ends, and how a tool call is read:",
      "",
      "- **Every run says how it ended** — `response.termination` is `\"done\"`, `\"not_possible\"`, `\"stuck\"`, `\"tool_failed\"` or `\"error\"`.",
      "- **A run that stops making progress is asked for its answer** instead of going round to its iteration cap (`max_turns_without_progress` now defaults to `2`).",
      "- **A tool that keeps failing on its own side ends the run `tool_failed`** rather than leaving the model to answer around it.",
      "- **A tool call written in a broken or unexpected shape is read and run** by default (`recover_lost_tool_calls=True`), and string arguments are decoded.",
      "- **A served or local model is measured once** for what it does with a tool, and `tool_calling_mode=\"auto\"` follows the result. `effgen doctor --probe MODEL` runs it; `probe_tool_calling()` and `ToolCallingProbe` are the two new names.",
      "- **One agent serves overlapping conversations** with `run(session=...)` and `stream(session=...)` without mixing them, and a streamed turn is saved to the agent's bound session.",
      "- **`reasoning_effort` reaches a model behind `base_url`, and Groq.**",
      "",
      "Where it falls short: small models given a search tool now cost noticeably more per run, because they are made to use it, and runs that use tools still make more model calls than they need to. The public surface grew from 251 names to 253. Ten changes are visible to existing code. See /docs/migration.",
      "",
      "The full list: /changelog · /docs/releases",
    ].join("\n"),
    tags: ["1.3.0", "v1.3.0", "new", "release", "latest", "changelog", "what's new", "minor release", "termination", "tool_failed", "capability probe", "probe_tool_calling", "ToolCallingProbe", "doctor --probe", "recover_lost_tool_calls", "max_turns_without_progress", "session"],
  },
  {
    id: 63,
    category: "Releases",
    question: "What's new in 1.2.0?",
    answer: [
      "1.2.0 came out on **27 September 2026**. It is about what a run costs, and whether you can see it:",
      "",
      "- **Every run keeps a ledger** — `response.ledger`, a `RunLedger`: model and tool calls, prompt, completion and cached tokens, cost, and where the time went (model, tools, caller, child runs, the framework).",
      "- **A tool result the model writes itself is never taken as the answer.**",
      "- **A provider's prompt cache is kept warm**, and its hits are read and priced where the provider reports them.",
      "- **A request carries less of the framework's own text**, and `reasoning_effort` reaches a blocking run.",
      "- **A model you serve yourself reads as unpriced rather than free**, and a spent cap no longer refuses it.",
      "- **`effgen bench`** measures an agent on your own tasks, with a noise band beside every difference.",
      "- **New settings**: `answer_style`, `max_turns_without_progress`, `recover_lost_tool_calls`.",
      "",
      "The public surface grew from 250 names to 251. Fourteen changes are visible to existing code. See /docs/migration.",
      "",
      "The full list: /changelog · /docs/releases",
    ].join("\n"),
    tags: ["1.2.0", "v1.2.0", "new", "release", "changelog", "what's new", "minor release", "ledger", "runledger", "cost", "bench", "answer_style", "prompt cache", "BudgetExceededError"],
  },
  {
    id: 62,
    category: "Releases",
    question: "What's new in 1.1.0?",
    answer: [
      "1.1.0 came out on **14 September 2026**. A run now keeps its conversation as typed steps — an `AgentThread` — instead of one growing string:",
      "",
      "- **A finished run says what it did** — `response.thread`, rendered the same by `effgen run --show-thread`, the run card, the debug inspector and the dashboard. `render_thread()` and `thread_as_text()` read it back.",
      "- **A run stays inside its budget** — `AgentConfig.context_budget` bounds the prompt tokens it may send, and the oldest material goes first.",
      "- **A saved run resumes where it stopped** — `agent.resume()` continues from the checkpoint's steps instead of restarting the task.",
      "- **One agent loop**, so `stream()` sends what `run()` sends.",
      "- **`prompt_protocol`** decides whether a run's conversation travels as one string or as messages; at the default, a run with tools continuing a session sends messages.",
      "- **`effgen run --json` works on a run that used a tool**, and its documents are scrubbed.",
      "",
      "The public surface grew from 225 names to 250. Eleven changes are visible to existing code. See /docs/migration.",
      "",
      "The full list: /changelog · /docs/releases",
    ].join("\n"),
    tags: ["1.1.0", "v1.1.0", "new", "release", "changelog", "what's new", "minor release", "thread", "agentthread", "context_budget", "prompt_protocol", "resume", "show-thread"],
  },
  {
    id: 61,
    category: "Releases",
    question: "What's new in 1.0.1?",
    answer: [
      "1.0.1 came out on **8 September 2026**. It fixes how a run reports what it did, what it puts in a prompt, and what its own bookkeeping costs:",
      "",
      "- **A run that stops without an answer says so** — `outcome`, `stop_reason` and `partial` on every response, and `RunStoppedError` under the default `raise_on_error=True`.",
      "- **Citation markers are opt-in** — `cite_sources=True` on the config or on `run()`.",
      "- **The loop guards no longer stop a run that is still making progress.**",
      "- **Every tool-calling path says what the tools are for**, picked from their declared category, with `tool_contract` and `tool_use` to change it.",
      "- **The budget check reads an index** instead of the whole spend ledger, and `effgen cost prune` keeps the ledger small.",
      "- **The Groq default is `openai/gpt-oss-20b`**, a model Groq still serves.",
      "",
      "Four of these are visible to existing code. See /docs/migration.",
      "",
      "The full list: /changelog · /docs/releases",
    ].join("\n"),
    tags: ["1.0.1", "v1.0.1", "new", "release", "changelog", "what's new", "point release", "stopped", "cite_sources", "groq"],
  },
  {
    id: 49,
    category: "Releases",
    question: "What's new in 1.0.0?",
    answer: [
      "1.0.0 is the first stable release, out on **14 August 2026**. The changes that alter how you write code:",
      "",
      "- **Any OpenAI-compatible server** — `provider=\"openai_compatible\"` with a `base_url`.",
      "- **`AgentResponse.tool_calls` carries the calls** — name, arguments, result, duration, error, iteration.",
      "- **Middleware** around the run, each model call and each tool call.",
      "- **`run(session=...)`** — one agent, many conversations.",
      "- **Pluggable compaction** — four strategies.",
      "- **Resumable workflows** — checkpoint a DAG and restart it.",
      "",
      "And the surfaces that are new: `effgen code`, `effgen top`, `effgen battle`, HTML reports and run cards, the model and pricing browser, the dashboard, the playground, durable run and session history.",
      "",
      "**Three breaking changes**: the Python floor is 3.11, `raise_on_error` defaults to `True`, and an unreachable backend raises. See /docs/migration.",
      "",
      "The full list: /changelog · /docs/releases",
    ].join("\n"),
    tags: ["1.0.0", "v1.0.0", "release", "stable", "features", "breaking"],
  },
  {
    id: 50,
    category: "Releases",
    question: "Where is the changelog?",
    answer: [
      "On this site at /changelog, grouped the way `CHANGELOG.md` is, with the breaking changes marked and their migrations beside them.",
      "",
      "In the documentation: /docs/releases for the release notes and /docs/migration for the upgrade path.",
      "",
      "In the repository: `CHANGELOG.md` for the detail and `NEWS.md` for the summary.",
    ].join("\n"),
    tags: ["changelog", "release notes", "history", "versions", "news", "what changed", "previous releases"],
  },

  // ── Examples & learning ───────────────────────────────────────────────────
  {
    id: 51,
    category: "Examples",
    question: "Where are the examples?",
    answer: [
      "On this site at /examples — complete programs with the output they actually produce.",
      "",
      "Shipped with the package, and runnable without leaving the terminal:",
      "",
      "```bash",
      "effgen examples list",
      "effgen examples run <name>",
      "```",
      "",
      "Longer walkthroughs are at /docs/tutorials, and /docs/cookbook has recipes for the multimodal work.",
    ].join("\n"),
    tags: ["examples", "sample", "demo", "tutorial", "cookbook", "learn", "walkthrough", "code sample", "how to"],
  },
  {
    id: 52,
    category: "Examples",
    question: "Is there something interactive I can try?",
    answer: [
      "Two things, both local.",
      "",
      "```bash",
      "effgen quickstart",
      "```",
      "",
      "walks you through picking a model, running an agent, and having it write and run code.",
      "",
      "```bash",
      "effgen serve",
      "```",
      "",
      "then open the playground in your browser: model and preset pickers, tool toggles, a tool trace, and copy-as-curl / CLI / Python for whatever you just ran. The dashboard beside it shows cost, latency percentiles and errors. Both are self-contained — no CDN, no third-party script.",
      "",
      "More: /docs/playground · /docs/dashboard",
    ].join("\n"),
    tags: ["playground", "try", "interactive", "demo", "quickstart", "dashboard", "browser", "web ui", "tutorial"],
  },

  // ── Community & project ───────────────────────────────────────────────────
  {
    id: 53,
    category: "Community",
    question: "How do I report a bug or ask for a feature?",
    answer: [
      "Open an issue: github.com/ctrl-gaurav/effGen/issues",
      "",
      "A useful report has the effGen version (`effgen --version`), the Python version, the provider and model, and the full traceback. `effgen doctor` output helps when the problem is environmental.",
      "",
      "Something about this website rather than the framework goes to the same tracker — say which page it was on.",
    ].join("\n"),
    tags: ["bug", "issue", "report", "feature request", "github", "problem", "help", "support", "contact"],
  },
  {
    id: 54,
    category: "Community",
    question: "How do I contribute?",
    answer: [
      "The repository is at github.com/ctrl-gaurav/effGen and contributions are welcome.",
      "",
      "```bash",
      "git clone https://github.com/ctrl-gaurav/effGen",
      "cd effGen",
      'pip install -e ".[dev]"',
      "pytest",
      "```",
      "",
      "A new tool is usually the easiest first contribution — `effgen create-plugin` scaffolds one. More on this site at /community.",
    ].join("\n"),
    tags: ["contribute", "contributing", "pull request", "pr", "development", "dev", "open source", "help out", "community"],
  },
  {
    id: 55,
    category: "Community",
    question: "How do I cite effGen?",
    answer: [
      "There is a preprint: arxiv.org/abs/2602.00887 — *EffGen: Enabling Small Language Models as Capable Autonomous Agents*.",
      "",
      "The BibTeX entry is on /community and in the repository's README.",
    ].join("\n"),
    tags: ["cite", "citation", "paper", "arxiv", "bibtex", "reference", "academic", "publication", "research"],
  },
  {
    id: 56,
    category: "General",
    question: "What licence is effGen under?",
    answer: [
      "Apache 2.0 — commercial use, modification and distribution are all permitted, with the usual attribution and notice requirements.",
      "",
      "The text is in the repository: github.com/ctrl-gaurav/effGen/blob/main/LICENSE",
    ].join("\n"),
    tags: ["license", "licence", "apache", "legal", "commercial", "open source", "free", "use"],
  },
  {
    id: 57,
    category: "General",
    question: "What is effGen, in one paragraph?",
    answer: [
      "effGen builds AI agents that work well with **small language models**. Most agent frameworks assume a large model and fall apart when you give them a small one; effGen is built the other way round, so a 1.5B model on your own hardware is a supported target rather than a degraded case.",
      "",
      "It is not only the loop. Tools, memory, RAG, guardrails, multi-agent teams, DAG workflows, evaluation, cost tracking, observability and an OpenAI-compatible server all come with it — and it still talks to every major provider when you want a large model.",
      "",
      "```bash",
      "pip install -U effgen",
      'effgen run "What is 24344 * 334?" -m openai:gpt-5-nano',
      "```",
      "",
      "More: /docs/introduction",
    ].join("\n"),
    tags: ["what is", "about", "overview", "introduction", "explain", "purpose", "slm", "small language model", "why"],
  },
  {
    id: 58,
    category: "General",
    question: "Does effGen work offline?",
    answer: [
      "Yes, if the model is local. Load weights with the `transformers`, `vllm`, `gguf` or `mlx` engine and nothing leaves the machine — tools that reach the network are the exception and you choose whether the agent has them.",
      "",
      "The web surfaces are self-contained too: the dashboard and playground draw their own charts and load no CDN script, which is enforced by a test rather than left to good intentions.",
      "",
      "More: /docs/local-models",
    ].join("\n"),
    tags: ["offline", "air gapped", "local", "no internet", "private", "self hosted", "on premise", "cdn", "isolated"],
  },
  {
    id: 59,
    category: "General",
    question: "Is there a TypeScript or JavaScript client?",
    answer: [
      "There is a client for the API server rather than a port of the framework — the agent loop is Python. Start `effgen serve` and talk to it over its OpenAI-compatible API from any language, including an existing OpenAI SDK pointed at a different `base_url`.",
      "",
      "More: /docs/clients · /docs/openai-api",
    ].join("\n"),
    tags: ["typescript", "javascript", "node", "client", "sdk", "language", "js", "ts", "rest", "other languages"],
  },
  {
    id: 60,
    category: "General",
    question: "Can I use it from a notebook or from VS Code?",
    answer: [
      "Both.",
      "",
      "```bash",
      'pip install "effgen[jupyter]"',
      "```",
      "",
      "gives you magics for running agents in a cell with the output rendered rather than dumped.",
      "",
      "There is also a VS Code extension in the repository under `tools/vscode-effgen/`.",
      "",
      "More: /docs/jupyter · /docs/vscode",
    ].join("\n"),
    tags: ["jupyter", "notebook", "vscode", "ide", "extension", "magics", "colab", "editor", "interactive"],
  },
];
